### ISSUE TITLE
02-AstroWeightCalculator

### ISSUE THREAD

**Issue by chelseamidgette** [OriginCodeAcademy/Cohort8#14]
1. Where can I find your repository? (Paste a link below)

https://github.com/chelseamidgette/AstroWeightCalculator

2. What was your best accomplishment in this project?

My best accomplishment was finally starting to grasp the concept of JavaScript syntax and how it works with HTML, as I had previously only really been familiar and comfortable with HTML and CSS, and using JavaScript's syntax was a major adjustment for me.

3. What was the most challenging piece of this project for you?

The most challenging aspect of this project, aside from getting used to JavaScript itself, was definitely trying to overcome my tendency to overthink the problem, especially when paired with my lack of knowledge of JavaScript. Finding the most efficient, simplest problem-solving methods will be a challenge that I look forward to tackling over the coming weeks with each language that we learn.

**Comment by seancahall** [comment]
you're doing well! just keep moving forward :-)
